// AUTO-GENERATED FILE. DO NOT EDIT.
// Run: npm run icons:labels

import type { DrinkIconKey, IngredientIconKey } from "./icons";

export const DRINK_ICON_LABELS: Record<DrinkIconKey, string> = {
  "adlay_almond_latte": "율무 아몬드 라떼",
  "adlay_cream_coldbrew": "율무 크림 콜드브루",
  "adlay_cream_frappe": "율무 크림 프라페",
  "adlay_latte": "율무 라떼",
  "aerocano": "에어로카노",
  "affogato": "아포가토",
  "air_rating_honey_matcha": "에어 라팅 허니 말차",
  "americano": "아메리카노",
  "apple_carrot_juice": "사과 당근 juice",
  "apple_cider_vinegar": "사과 사이다 vinegar",
  "apple_citron_tea": "사과 유자 티",
  "apple_hibiscus_tea": "사과 히비스커스 티",
  "apple_juice": "사과 juice",
  "apple_muscat_yogurt_smoothie": "사과 머스캣 요거트 스무디",
  "banana_cafe_latte": "바나나 카페 라떼",
  "banana_coffee_shake": "바나나 커피 쉐이크",
  "banana_macadamia_oat_frappuccino": "바나나 마카다미아 오트 프라푸치노",
  "banana_milk": "바나나 밀크",
  "banana_milkshake": "바나나 밀크쉐이크",
  "banana_pongcrush": "바나나 퐁크러쉬",
  "banana_yogurt_smoothie": "바나나 요거트 스무디",
  "basak_pistachio_chocolate_cream_frappuccino": "basak 피스타치오 초코 크림 프라푸치노",
  "basak_pistachio_vanilla_cream_cold_brew": "basak 피스타치오 바닐라 크림 콜드 브루",
  "baseball_green_plum_green_tea": "baseball 그린 자두 그린 티",
  "bergamot_coldbrew": "bergamot 콜드브루",
  "bergamot_jeju_malcha_cream_frappuccino": "bergamot 제주 말차 크림 프라푸치노",
  "bergamot_strawberry_cream_frappuccino": "bergamot 딸기 크림 프라푸치노",
  "berry_pearl_strawberry_juice": "베리 펄 딸기 juice",
  "berry_pearl_strawberry_latte": "베리 펄 딸기 라떼",
  "black_milk_tea_ice_cream_float": "블랙 밀크 티 아이스 크림 플로트",
  "black_milk_tea_pearl_shake": "블랙 밀크 티 펄 쉐이크",
  "black_sesame_cream_coffee": "블랙 sesame 크림 커피",
  "black_sesame_milk_tea": "블랙 sesame 밀크 티",
  "black_tea": "블랙 티",
  "black_tiramisu_milk_tea": "블랙 티라미수 밀크 티",
  "black_white_coldbrew": "블랙 화이트 콜드브루",
  "blue_lemon_ade": "블루 레몬 ade",
  "blueberry_ade": "블루베리 ade",
  "blueberry_juice": "블루베리 juice",
  "blueberry_latte": "블루베리 라떼",
  "blueberry_plum_juice": "블루베리 자두 juice",
  "blueberry_smoothie": "블루베리 스무디",
  "blueberry_yogurt_smoothie": "블루베리 요거트 스무디",
  "bori_tea": "bori 티",
  "brewed_coffee": "brewed 커피",
  "brown_sugar_bubble_latte": "브라운 슈가 버블 라떼",
  "brown_sugar_latte": "브라운 슈가 라떼",
  "brownsugar_bubble_cafe_latte": "브라운슈가 버블 카페 라떼",
  "brownsugar_coldbrew_latte": "브라운슈가 콜드브루 라떼",
  "brownsugar_jewelry_cheese_foam_smoothie": "브라운슈가 쥬얼리 cheese foam 스무디",
  "brownsugar_milk_tea_ice_cream_float": "브라운슈가 밀크 티 아이스 크림 플로트",
  "brownsugar_milk_tea_pearl_shake": "브라운슈가 밀크 티 펄 쉐이크",
  "brownsugar_signature_milk_tea_with_mini_pearl": "브라운슈가 시그니처 밀크 티 위드 미니 펄",
  "brownsugar_signature_milk_tea_with_pearl": "브라운슈가 시그니처 밀크 티 위드 펄",
  "bubble_tea": "버블 티",
  "bubble_tea_1l": "버블 티 1l",
  "bukhansan_lemon_earlgrey_blended": "bukhansan 레몬 얼그레이 blended",
  "burnt_caramel_latte": "burnt 카라멜 라떼",
  "cafe_latte": "카페 라떼",
  "cafe_mocha": "카페 모카",
  "calamansi_ade": "깔라만시 ade",
  "calamansi_tea": "깔라만시 티",
  "camomile_tea": "캐모마일 티",
  "candy_soda_milkshake": "candy 소다 밀크쉐이크",
  "cappuccino": "카푸치노",
  "caramel_cafe_mocha": "카라멜 카페 모카",
  "caramel_frappuccino": "카라멜 프라푸치노",
  "caramel_machiato": "카라멜 마키아토",
  "cherry_ade": "cherry ade",
  "cherry_blossom_peach_cream_frappuccino": "cherry 블로썸 복숭아 크림 프라푸치노",
  "cherry_coke": "cherry coke",
  "cherry_juice": "cherry juice",
  "cherry_plum_energy_fizzio": "cherry 자두 에너지 피지오",
  "chestnut_chocolate_latte": "밤 초코 라떼",
  "chestnut_latte": "밤 라떼",
  "chestnut_smoothie": "밤 스무디",
  "choco_banana_macadamia_oat_frappuccino": "초코 바나나 마카다미아 오트 프라푸치노",
  "choco_choco_smoothie": "초코 초코 스무디",
  "choco_gelato_matcha_tea_latte": "초코 gelato 말차 티 라떼",
  "choco_jeju_green_smoothie": "초코 제주 그린 스무디",
  "choco_mello_smoothie": "초코 멜로 스무디",
  "choco_milk": "초코 밀크",
  "choco_pistachio_smoothie": "초코 피스타치오 스무디",
  "chocolate_banana_paiksccino_basic": "초코 바나나 빽스치노 기본",
  "chocolate_banana_paiksccino_soft": "초코 바나나 빽스치노 소프트",
  "chocolate_cookie_and_cream_smoothie": "초코 쿠키 and 크림 스무디",
  "chocolate_cream_chip_frappuccino": "초코 크림 칩 프라푸치노",
  "chocolate_earlgrey_milk_tea": "초코 얼그레이 밀크 티",
  "chocolate_fish_milk": "초코 피쉬 밀크",
  "chocolate_honey_pongcrush": "초코 허니 퐁크러쉬",
  "chocolate_milk_tea": "초코 밀크 티",
  "chocolate_milk_tea_cheese_foam": "초코 밀크 티 cheese foam",
  "chocolate_paiksccino_basic": "초코 빽스치노 기본",
  "chocolate_paiksccino_soft": "초코 빽스치노 소프트",
  "chocolate_yogurt_smoothie": "초코 요거트 스무디",
  "choux_cream_latte": "슈 크림 라떼",
  "choux_cream_matcha_latte": "슈 크림 말차 라떼",
  "choux_cream_milk_tea": "슈 크림 밀크 티",
  "choux_cream_strawberry_latte": "슈 크림 딸기 라떼",
  "choux_foam_latte": "슈 foam 라떼",
  "choux_foam_matcha_latte": "슈 foam 말차 라떼",
  "choux_foam_strawberry_latte": "슈 foam 딸기 라떼",
  "cider": "사이다",
  "cinnamon_sugar_cappuccino": "시나몬 슈가 카푸치노",
  "citron_ginger_tea": "유자 생강 티",
  "citrus_garden_mint_tea": "시트러스 가든 민트 티",
  "classic_milktea_blended": "classic 밀크티 blended",
  "cloud_coco_malcha": "cloud 코코 말차",
  "coconut_cafe_latte": "코코넛 카페 라떼",
  "coconut_coffee_smoothie": "코코넛 커피 스무디",
  "coconut_coldbrew_latte": "코코넛 콜드브루 라떼",
  "coconut_coldbrew_smoothie": "코코넛 콜드브루 스무디",
  "coffee_choco_chip_gelato_choux_cream_latte": "커피 초코 칩 gelato 슈 크림 라떼",
  "coffee_frappe": "커피 프라페",
  "coffee_milkshake": "커피 밀크쉐이크",
  "coffee_oranmang": "커피 오렌지 망고",
  "coke": "coke",
  "coldbrew": "콜드브루",
  "coldbrew_brownsugar_latte": "콜드브루 브라운슈가 라떼",
  "coldbrew_float": "콜드브루 플로트",
  "coldbrew_malt": "콜드브루 malt",
  "combu_tea_plum": "combu 티 자두",
  "combu_tea_shine_muscat": "combu 티 샤인 머스캣",
  "condensed_milk_coldbrew_latte": "연유 밀크 콜드브루 라떼",
  "condensed_milk_creamy_spanner": "연유 밀크 크리미 spanner",
  "cookie_chocolate_frappe": "쿠키 초코 프라페",
  "cookie_chocolate_latte": "쿠키 초코 라떼",
  "cookie_crunch_paiksccino_basic": "쿠키 crunch 빽스치노 기본",
  "cookie_crunch_paiksccino_soft": "쿠키 crunch 빽스치노 소프트",
  "cookie_frappe": "쿠키 프라페",
  "cookie_milkshake": "쿠키 밀크쉐이크",
  "cool_lime_fizzio": "쿨 lime 피지오",
  "cool_lime_smoothie": "쿨 lime 스무디",
  "corn_fish_milk_tea": "옥수수 피쉬 밀크 티",
  "cortado": "cortado",
  "cream_matcha_latte": "크림 말차 라떼",
  "creamy_coldbrew_caramel": "크리미 콜드브루 카라멜",
  "crunchy_pistachio_frappe": "crunchy 피스타치오 프라페",
  "crunky_chocolate_latte": "crunky 초코 라떼",
  "crunky_chocolate_smoothie": "crunky 초코 스무디",
  "cube_condensed_milk_latte": "cube 연유 밀크 라떼",
  "cube_latte": "cube 라떼",
  "dalgona_latte": "dalgona 라떼",
  "deep_choco_berry_latte": "딥 초코 베리 라떼",
  "deep_choco_milk_shake": "딥 초코 밀크 쉐이크",
  "deep_matcha_berry_latte": "딥 말차 베리 라떼",
  "deep_milk_shake": "딥 밀크 쉐이크",
  "deep_vanilla_double_shot": "딥 바닐라 더블 shot",
  "dolce_coldbrew": "돌체 콜드브루",
  "double_chocolate_latte": "더블 초코 라떼",
  "double_coffee_chip_frappe": "더블 커피 칩 프라페",
  "double_espresso_chip_frappuccino": "더블 에스프레소 칩 프라푸치노",
  "double_espresso_cream_latte": "더블 에스프레소 크림 라떼",
  "double_matcha_milk_tea": "더블 말차 밀크 티",
  "double_shot": "더블 shot",
  "dubai_chcolate_crush": "dubai chcolate crush",
  "earlgrey_chocolate_latte": "얼그레이 초코 라떼",
  "earlgrey_lemon_tea": "얼그레이 레몬 티",
  "earlgrey_matcha_milk_tea_pearl": "얼그레이 말차 밀크 티 펄",
  "earlgrey_milk_tea": "얼그레이 밀크 티",
  "earlgrey_tea": "얼그레이 티",
  "earlgrey_vanilla_tea_latte": "얼그레이 바닐라 티 라떼",
  "einspanner_latte": "einspanner 라떼",
  "energy_drink": "에너지 drink",
  "english_breakfast_tea": "잉글리시 breakfast 티",
  "espresso": "에스프레소",
  "espresso_con_panna": "에스프레소 con 판나",
  "espresso_cream_french_vanilla_latte": "에스프레소 크림 french 바닐라 라떼",
  "espresso_frappuccino": "에스프레소 프라푸치노",
  "espresso_macchiato": "에스프레소 마키아토",
  "flat_peach_ice_tea_earlgrey": "flat 복숭아 아이스 티 얼그레이",
  "fluffy_panda_hot_chocolate": "fluffy 판다 핫 초코",
  "fluffy_panda_ice_chocolate": "fluffy 판다 아이스 초코",
  "french_fries_milkshake": "french fries 밀크쉐이크",
  "french_vanilla_malcha_latte": "french 바닐라 말차 라떼",
  "gold_kiwi_juice": "골드 키위 juice",
  "gold_mango_smoothie": "골드 망고 스무디",
  "golden_java_chip_smoothie": "golden 자바 칩 스무디",
  "golden_mandarin_hop_fizzio": "golden mandarin hop 피지오",
  "grain_latte": "grain 라떼",
  "grape_blossom_mint_tea": "포도 블로썸 민트 티",
  "grape_juice": "포도 juice",
  "grapefruit_ade": "자몽 ade",
  "grapefruit_chamomile_tea": "자몽 chamomile 티",
  "grapefruit_honey_black_tea": "자몽 허니 블랙 티",
  "grapefruit_honey_lemon_blended": "자몽 허니 레몬 blended",
  "grapefruit_jasmin_tea": "자몽 자스민 티",
  "grapefruit_juice": "자몽 juice",
  "grapefruit_tea": "자몽 티",
  "grapefruit_yogurt": "자몽 요거트",
  "greek_yogurt_grapefruit_crush": "greek 요거트 자몽 crush",
  "greek_yogurt_grapefruit_mango_mini_pearl_crush": "greek 요거트 자몽 망고 미니 펄 crush",
  "greek_yogurt_mango_crush": "greek 요거트 망고 crush",
  "greek_yogurt_peach_crush": "greek 요거트 복숭아 crush",
  "greek_yogurt_pearl_crush": "greek 요거트 펄 crush",
  "greek_yogurt_strawberry_crush": "greek 요거트 딸기 crush",
  "green_grape_ade": "그린 포도 ade",
  "green_grape_cream_cheese_foam": "그린 포도 크림 cheese foam",
  "green_grape_flower": "그린 포도 플라워",
  "green_grape_jasmin_tea": "그린 포도 자스민 티",
  "green_grape_smoothie": "그린 포도 스무디",
  "green_tangerine_ginger_tea": "그린 tangerine 생강 티",
  "green_tangerine_sparkling_tea": "그린 tangerine 스파클링 티",
  "green_tangerine_tea": "그린 tangerine 티",
  "green_tea": "그린 티",
  "green_tea_frappe": "그린 티 프라페",
  "greentea_bubble_tea": "녹차 버블 티",
  "herb_tea": "허브 티",
  "hisbiscus_blend_tea": "hisbiscus blend 티",
  "honey_hotteok_cream_frappuccino": "허니 호떡 크림 프라푸치노",
  "honey_hotteok_latte": "허니 호떡 라떼",
  "hot_black_sesame_cream_coffee": "핫 블랙 sesame 크림 커피",
  "hot_chocolate": "핫 초코",
  "ice_adlay_almond_latte": "아이스 율무 아몬드 라떼",
  "ice_adlay_latte": "아이스 율무 라떼",
  "ice_americano": "아이스 아메리카노",
  "ice_apple_citron_tea": "아이스 사과 유자 티",
  "ice_apple_hibiscus_tea": "아이스 사과 히비스커스 티",
  "ice_banana_cafe_latte": "아이스 바나나 카페 라떼",
  "ice_black_sesame_milk_tea": "아이스 블랙 sesame 밀크 티",
  "ice_black_tea": "아이스 블랙 티",
  "ice_black_tiramisu_milk_tea": "아이스 블랙 티라미수 밀크 티",
  "ice_brownsugar_bubble_milk_tea": "아이스 브라운슈가 버블 밀크 티",
  "ice_brownsugar_milk_tea": "아이스 브라운슈가 밀크 티",
  "ice_brownsugar_signature_milk_tea_with_pearl": "아이스 브라운슈가 시그니처 밀크 티 위드 펄",
  "ice_bubble_tea": "아이스 버블 티",
  "ice_cafe_latte": "아이스 카페 라떼",
  "ice_cafe_mocha": "아이스 카페 모카",
  "ice_cafelatte": "아이스 cafelatte",
  "ice_calamansi_tea": "아이스 깔라만시 티",
  "ice_camomile_tea": "아이스 캐모마일 티",
  "ice_cappuccino": "아이스 카푸치노",
  "ice_caramel_cafe_mocha": "아이스 카라멜 카페 모카",
  "ice_caramel_machiato": "아이스 카라멜 마키아토",
  "ice_chestnut_chocolate_latte": "아이스 밤 초코 라떼",
  "ice_chestnut_latte": "아이스 밤 라떼",
  "ice_chocolate": "아이스 초코",
  "ice_chocolate_earlgrey_milk_tea": "아이스 초코 얼그레이 밀크 티",
  "ice_chocolate_milk_tea": "아이스 초코 밀크 티",
  "ice_chocolate_milk_tea_cheese_foam": "아이스 초코 밀크 티 cheese foam",
  "ice_choux_cream_latte": "아이스 슈 크림 라떼",
  "ice_choux_cream_matcha_latte": "아이스 슈 크림 말차 라떼",
  "ice_choux_cream_milk_tea": "아이스 슈 크림 밀크 티",
  "ice_choux_foam_latte": "아이스 슈 foam 라떼",
  "ice_choux_foam_matcha_latte": "아이스 슈 foam 말차 라떼",
  "ice_cinnamon_sugar_cappuccino": "아이스 시나몬 슈가 카푸치노",
  "ice_citron_tea": "아이스 유자 티",
  "ice_coconut_cafe_latte": "아이스 코코넛 카페 라떼",
  "ice_coconut_coldbrew_latte": "아이스 코코넛 콜드브루 라떼",
  "ice_coldbrew_brownsugar_latte": "아이스 콜드브루 브라운슈가 라떼",
  "ice_condensed_milk_coldbrew_latte": "아이스 연유 밀크 콜드브루 라떼",
  "ice_cookie_chocolate_latte": "아이스 쿠키 초코 라떼",
  "ice_crunky_chocolate_latte": "아이스 crunky 초코 라떼",
  "ice_crush_melon": "아이스 crush 멜론",
  "ice_double_chocolate_latte": "아이스 더블 초코 라떼",
  "ice_double_espresso_cream_latte": "아이스 더블 에스프레소 크림 라떼",
  "ice_double_matcha_milk_tea": "아이스 더블 말차 밀크 티",
  "ice_dubai_chocolate_malcha": "아이스 dubai 초코 말차",
  "ice_dubai_chocolate_mocha": "아이스 dubai 초코 모카",
  "ice_earlgrey_chocolate_latte": "아이스 얼그레이 초코 라떼",
  "ice_earlgrey_lemon_tea": "아이스 얼그레이 레몬 티",
  "ice_earlgrey_milk_tea": "아이스 얼그레이 밀크 티",
  "ice_earlgrey_tea": "아이스 얼그레이 티",
  "ice_earlgrey_vanilla_tea_latte": "아이스 얼그레이 바닐라 티 라떼",
  "ice_einspanner": "아이스 einspanner",
  "ice_english_breakfast_tea": "아이스 잉글리시 breakfast 티",
  "ice_espresso_cream_french_vanilla_latte": "아이스 에스프레소 크림 french 바닐라 라떼",
  "ice_french_vanilla_malcha_latte": "아이스 french 바닐라 말차 라떼",
  "ice_ginger_tea": "아이스 생강 티",
  "ice_grain_latte": "아이스 grain 라떼",
  "ice_grape_blossom_mint_tea": "아이스 포도 블로썸 민트 티",
  "ice_grapefruit_chamomile_tea": "아이스 자몽 chamomile 티",
  "ice_grapefruit_honey_black_tea": "아이스 자몽 허니 블랙 티",
  "ice_grapefruit_jasmin_tea": "아이스 자몽 자스민 티",
  "ice_grapefruit_tea": "아이스 자몽 티",
  "ice_green_grape_jasmin_tea": "아이스 그린 포도 자스민 티",
  "ice_green_tangerine_tea": "아이스 그린 tangerine 티",
  "ice_green_tea": "아이스 그린 티",
  "ice_green_tea_latte": "아이스 그린 티 라떼",
  "ice_greentea_bubble_tea": "아이스 녹차 버블 티",
  "ice_herb_tea": "아이스 허브 티",
  "ice_hibiscus_blend_tea": "아이스 히비스커스 blend 티",
  "ice_honey_hotteok_latte": "아이스 허니 호떡 라떼",
  "ice_injeolmi_cream_latte": "아이스 injeolmi 크림 라떼",
  "ice_injeolmi_jeju_malcha_latte": "아이스 injeolmi 제주 말차 라떼",
  "ice_jasmin_milk_tea": "아이스 자스민 밀크 티",
  "ice_jasmin_tea": "아이스 자스민 티",
  "ice_jeju_green_milk_tea": "아이스 제주 그린 밀크 티",
  "ice_jeju_hassaku_orange_grapefruit_honey_black_tea": "아이스 제주 hassaku orange 자몽 허니 블랙 티",
  "ice_jujube_latte": "아이스 대추 라떼",
  "ice_jujube_tea": "아이스 대추 티",
  "ice_lavender_cafe_breve": "아이스 lavender 카페 breve",
  "ice_lemon_chamomile_blend_tea": "아이스 레몬 chamomile blend 티",
  "ice_lemon_earlgrey_tea": "아이스 레몬 얼그레이 티",
  "ice_lemon_ginger_tea": "아이스 레몬 생강 티",
  "ice_lemon_jasmin_tea": "아이스 레몬 자스민 티",
  "ice_lemon_tea": "아이스 레몬 티",
  "ice_maesil_tea": "아이스 maesil 티",
  "ice_malcha_tiramisu_latte": "아이스 말차 티라미수 라떼",
  "ice_marshmallow_chocolate_latte": "아이스 marshmallow 초코 라떼",
  "ice_matcha_cream_latte": "아이스 말차 크림 라떼",
  "ice_matcha_latte": "아이스 말차 라떼",
  "ice_matcha_tiramisu_milk_tea": "아이스 말차 티라미수 밀크 티",
  "ice_matchalatte": "아이스 matchalatte",
  "ice_merry_double_nuts_chocolate_latte": "아이스 merry 더블 nuts 초코 라떼",
  "ice_micho": "아이스 micho",
  "ice_milk_caramel_latte": "아이스 밀크 카라멜 라떼",
  "ice_milk_tea": "아이스 밀크 티",
  "ice_milktea": "아이스 밀크티",
  "ice_mint_cafe_mocha": "아이스 민트 카페 모카",
  "ice_mint_chocolate_latte": "아이스 민트 초코 라떼",
  "ice_mojito_lemon_black_tea": "아이스 mojito 레몬 블랙 티",
  "ice_omija_tea": "아이스 오미자 티",
  "ice_oolong_milk_tea": "아이스 oolong 밀크 티",
  "ice_oolong_tea": "아이스 oolong 티",
  "ice_oolong_tea_coconut_milk_foam": "아이스 oolong 티 코코넛 밀크 foam",
  "ice_oozy_deep_matcha_latte": "아이스 oozy 딥 말차 라떼",
  "ice_oozy_real_chocolate_latte": "아이스 oozy real 초코 라떼",
  "ice_orange_grapefruit_black_tea": "아이스 orange 자몽 블랙 티",
  "ice_original_mixed_coffee": "아이스 original mixed 커피",
  "ice_passion_fruit_hibiscus": "아이스 패션 프루트 히비스커스",
  "ice_peach_oolong_sweet_tea": "아이스 복숭아 oolong 스위트 티",
  "ice_perilla_leaf_cafe_latte": "아이스 perilla leaf 카페 라떼",
  "ice_pineapple_mint_tea": "아이스 파인애플 민트 티",
  "ice_pistachio_milk_tea": "아이스 피스타치오 밀크 티",
  "ice_pistachio_tiramisu_milk_tea": "아이스 피스타치오 티라미수 밀크 티",
  "ice_puer_tea": "아이스 puer 티",
  "ice_rooibos_tea": "아이스 rooibos 티",
  "ice_rosemary_tea": "아이스 rosemary 티",
  "ice_royal_milk_tea_latte": "아이스 royal 밀크 티 라떼",
  "ice_ruby_rose_chocolate": "아이스 ruby rose 초코",
  "ice_salted_sweet_potato_milk_tea": "아이스 salted 스위트 potato 밀크 티",
  "ice_songpa_latte": "아이스 songpa 라떼",
  "ice_ssanghwa_latte": "아이스 ssanghwa 라떼",
  "ice_ssanghwa_tea": "아이스 ssanghwa 티",
  "ice_strawberry_raspberry_cheese_foam": "아이스 딸기 raspberry cheese foam",
  "ice_sujeonggwa": "아이스 sujeonggwa",
  "ice_sweet_potato_cafe_latte": "아이스 스위트 potato 카페 라떼",
  "ice_sweet_potato_latte": "아이스 스위트 potato 라떼",
  "ice_taro_bubble_tea": "아이스 taro 버블 티",
  "ice_taro_milk_tea": "아이스 taro 밀크 티",
  "ice_tea_with_mango": "아이스 티 위드 망고",
  "ice_tea_with_shot": "아이스 티 위드 shot",
  "ice_tea_with_shot_mango": "아이스 티 위드 shot 망고",
  "ice_tiramisu_chocolate": "아이스 티라미수 초코",
  "ice_toffeenut_latte": "아이스 toffeenut 라떼",
  "ice_uiamho_purple_lavender_tea_latte": "아이스 uiamho purple lavender 티 라떼",
  "ice_vanilla_bean_latte": "아이스 바닐라 bean 라떼",
  "ice_vanilla_cafe_mocha": "아이스 바닐라 카페 모카",
  "ice_vin_chaud": "아이스 vin chaud",
  "ice_white_chocolate_mocha": "아이스 화이트 초코 모카",
  "ice_white_salt_milk_tea": "아이스 화이트 salt 밀크 티",
  "ice_youthberry_tea": "아이스 youthberry 티",
  "ice_yuja_mint_tea": "아이스 yuja 민트 티",
  "ice_yuja_white_tea_vin_chaud": "아이스 yuja 화이트 티 vin chaud",
  "ice_zesty_lychee_tea": "아이스 zesty 리치 티",
  "icecream_cafe_latte": "icecream 카페 라떼",
  "icecream_cafe_mocha": "icecream 카페 모카",
  "icecream_vanilla_latte": "icecream 바닐라 라떼",
  "injeolmi_cream_latte": "injeolmi 크림 라떼",
  "injeolmi_cupbing": "injeolmi cupbing",
  "injeolmi_jeju_malcha_cream_frappuccino": "injeolmi 제주 말차 크림 프라푸치노",
  "injeolmi_jeju_malcha_latte": "injeolmi 제주 말차 라떼",
  "jasmin_coco_matcha_foam": "자스민 코코 말차 foam",
  "jasmin_milk_tea": "자스민 밀크 티",
  "jasmin_tea": "자스민 티",
  "java_chip_frappuccino": "자바 칩 프라푸치노",
  "jeju_black_sesame_cream_frappuccino": "제주 블랙 sesame 크림 프라푸치노",
  "jeju_forest_reserve_coldbrew": "제주 forest reserve 콜드브루",
  "jeju_forest_reserve_espresso_latte": "제주 forest reserve 에스프레소 라떼",
  "jeju_green_milk_tea": "제주 그린 밀크 티",
  "jeju_green_smoothie": "제주 그린 스무디",
  "jeju_hassaku_orange_fizzio": "제주 hassaku orange 피지오",
  "jeju_hassaku_orange_frozen_fizzio": "제주 hassaku orange 프로즌 피지오",
  "jeju_hassaku_orange_grapefruit_honey_black_tea": "제주 hassaku orange 자몽 허니 블랙 티",
  "jeju_mugwort_cream_frappuccino": "제주 mugwort 크림 프라푸치노",
  "jeju_tangerine_blended": "제주 tangerine blended",
  "jeju_tangerine_juice": "제주 tangerine juice",
  "jujube_latte": "대추 라떼",
  "jujube_tea": "대추 티",
  "kiwi_juice": "키위 juice",
  "lavender_cafe_breve": "lavender 카페 breve",
  "lemon_ade": "레몬 ade",
  "lemon_chamomile_blend_tea": "레몬 chamomile blend 티",
  "lemon_earlgrey_tea": "레몬 얼그레이 티",
  "lemon_ginger_tea": "레몬 생강 티",
  "lemon_ice_tea": "레몬 아이스 티",
  "lemon_jasmin_tea": "레몬 자스민 티",
  "lemon_tea": "레몬 티",
  "lemon_yogurt": "레몬 요거트",
  "lemon_yogurt_smoothie": "레몬 요거트 스무디",
  "lemonicano": "lemonicano",
  "light_pink_grapefruit_fizzio": "light pink 자몽 피지오",
  "light_vanilla_cream_coldbrew": "light 바닐라 크림 콜드브루",
  "lime_mojito": "lime mojito",
  "maeshotchu": "maeshotchu",
  "maesil_ade": "maesil ade",
  "maesil_tea": "maesil 티",
  "malcha_tiramisu_latte": "말차 티라미수 라떼",
  "malcha_waterfall_yuja_blended": "말차 waterfall yuja blended",
  "mango_ade": "망고 ade",
  "mango_banana_blended": "망고 바나나 blended",
  "mango_foam_jasmin_teapleasure": "망고 foam 자스민 teapleasure",
  "mango_guaba_carrot_juice": "망고 guaba 당근 juice",
  "mango_jasmin_tea_white_pearl_1l": "망고 자스민 티 화이트 펄 1l",
  "mango_juice": "망고 juice",
  "mango_latte": "망고 라떼",
  "mango_orenmang": "망고 orenmang",
  "mango_passion_fruit_blended": "망고 패션 프루트 blended",
  "mango_yogurt": "망고 요거트",
  "mango_yogurt_smoothie": "망고 요거트 스무디",
  "mango_yogurt_white_pearl": "망고 요거트 화이트 펄",
  "marshmallow_chocolate_latte": "marshmallow 초코 라떼",
  "matcha_coldbrew_latte": "말차 콜드브루 라떼",
  "matcha_cream_mango_smoothie": "말차 크림 망고 스무디",
  "matcha_frappe": "말차 프라페",
  "matcha_gelato_strawberry_frappe": "말차 gelato 딸기 프라페",
  "matcha_latte": "말차 라떼",
  "matcha_paiksccino_basic": "말차 빽스치노 기본",
  "matcha_paiksccino_soft": "말차 빽스치노 소프트",
  "matcha_red_bean_bingsu_shake": "말차 red bean bingsu 쉐이크",
  "matcha_shot_yuju_smoothie": "말차 shot yuju 스무디",
  "matcha_tiramisu_milk_tea": "말차 티라미수 밀크 티",
  "matcha_yuju_shot_smoothie": "말차 yuju shot 스무디",
  "matchalatte": "matchalatte",
  "mega_ade": "mega ade",
  "mega_chocolate": "mega 초코",
  "melon_melon_jelly_crush": "멜론 멜론 jelly crush",
  "melon_melon_jelly_milk_tea": "멜론 멜론 jelly 밀크 티",
  "melon_melon_milk_tea": "멜론 멜론 밀크 티",
  "melon_soda": "멜론 소다",
  "merry_double_nuts_chocolate_latte": "merry 더블 nuts 초코 라떼",
  "micho_ade": "micho ade",
  "milk": "밀크",
  "milk_caramel_latte": "밀크 카라멜 라떼",
  "milk_cookie_and_cream_smoothie": "밀크 쿠키 and 크림 스무디",
  "milk_tea": "밀크 티",
  "milkshake": "밀크쉐이크",
  "mini_pearl_mango_crush": "미니 펄 망고 crush",
  "mini_pearl_mango_milk": "미니 펄 망고 밀크",
  "mini_pearl_mango_milk_real_mango": "미니 펄 망고 밀크 real 망고",
  "mini_pearl_strawberry_crush": "미니 펄 딸기 crush",
  "mini_pearl_strawberry_milk_tea": "미니 펄 딸기 밀크 티",
  "mint_cafe_mocha": "민트 카페 모카",
  "mint_chocolate_latte": "민트 초코 라떼",
  "mint_chocolate_paiksccino_basic": "민트 초코 빽스치노 기본",
  "mint_chocolate_paiksccino_soft": "민트 초코 빽스치노 소프트",
  "mint_coldbrew": "민트 콜드브루",
  "mint_cookie_smoothie": "민트 쿠키 스무디",
  "mint_frappe": "민트 프라페",
  "misutgaru": "misutgaru",
  "mix_coffee": "mix 커피",
  "mix_coffee_blend_with_grain_powder": "mix 커피 blend 위드 grain powder",
  "mocha_java_chip_frappe": "모카 자바 칩 프라페",
  "mojito_lemon_black_tea": "mojito 레몬 블랙 티",
  "nitro_coldbrew": "nitro 콜드브루",
  "nitro_vanilla_cream": "nitro 바닐라 크림",
  "nurungji_crisip_frappe": "nurungji crisip 프라페",
  "oat_coldbrew": "오트 콜드브루",
  "omija_lemon_ade": "오미자 레몬 ade",
  "omija_tea": "오미자 티",
  "omotesando_coffee": "omotesando 커피",
  "oolong_milk_tea": "oolong 밀크 티",
  "oolong_tea": "oolong 티",
  "oolong_tea_coconut_milk_foam": "oolong 티 코코넛 밀크 foam",
  "oozy_matcha_yuja_tea": "oozy 말차 yuja 티",
  "oozy_real_chocolate_latte": "oozy real 초코 라떼",
  "orange_carrot_juice": "orange 당근 juice",
  "orange_creamy_spanner": "orange 크리미 spanner",
  "orange_grapefruit_black_tea": "orange 자몽 블랙 티",
  "orange_juice": "orange juice",
  "oreo_chocolate_latte": "oreo 초코 라떼",
  "original_mixed_coffee": "original mixed 커피",
  "original_paiksccino_basic": "original 빽스치노 기본",
  "original_paiksccino_soft": "original 빽스치노 소프트",
  "passion_fruit_ade": "패션 프루트 ade",
  "passion_fruit_hibiscus": "패션 프루트 히비스커스",
  "passion_fruit_smoothie": "패션 프루트 스무디",
  "peach_ade": "복숭아 ade",
  "peach_hot_tea": "복숭아 핫 티",
  "peach_ice_tea": "복숭아 아이스 티",
  "peach_juice": "복숭아 juice",
  "peach_mango_blended": "복숭아 망고 blended",
  "peach_mango_smoothie": "복숭아 망고 스무디",
  "peach_oolon_sweet_tea": "복숭아 oolon 스위트 티",
  "peach_strawberry_fizzio": "복숭아 딸기 피지오",
  "peach_yogurt_smoothie": "복숭아 요거트 스무디",
  "peanut_butter_chocolate_frappe": "땅콩 butter 초코 프라페",
  "peanut_cream_latte": "땅콩 크림 라떼",
  "perilla_leaf_cafe_latte": "perilla leaf 카페 라떼",
  "perilla_leaf_smoothie": "perilla leaf 스무디",
  "persimmon_smoothie": "감 스무디",
  "pineapple_juice": "파인애플 juice",
  "pineapple_mint_tea": "파인애플 민트 티",
  "pineapple_smoothie": "파인애플 스무디",
  "pink_peach_milk_tea": "pink 복숭아 밀크 티",
  "pistachio_milk_tea": "피스타치오 밀크 티",
  "pistachio_paiksccino_basic": "피스타치오 빽스치노 기본",
  "pistachio_paiksccino_soft": "피스타치오 빽스치노 소프트",
  "pistachio_tiramisu_milk_tea": "피스타치오 티라미수 밀크 티",
  "plain_pongcrush": "plain 퐁크러쉬",
  "plain_yogurt_smoothie": "plain 요거트 스무디",
  "pongdangccino_coffee": "pongdangccino 커피",
  "pongdangccino_grain_powder": "pongdangccino grain powder",
  "protein_shake_banana": "protein 쉐이크 바나나",
  "protein_shake_chocolate": "protein 쉐이크 초코",
  "puer_tea": "puer 티",
  "read_bean_injeolmi_milkshake": "read bean injeolmi 밀크쉐이크",
  "real_chocolate_frappe": "real 초코 프라페",
  "real_chocolate_latte": "real 초코 라떼",
  "real_persimmon_juice": "real 감 juice",
  "red_power_passion_tea": "red power 패션 티",
  "redbull_ade": "redbull ade",
  "redbull_with_honey_espresso": "redbull 위드 허니 에스프레소",
  "reserve_friends_cinnamon_dolce_foam_cappuccino": "reserve friends 시나몬 돌체 foam 카푸치노",
  "reserve_ice_friends_cinnamon_dolce_foam_cappuccino": "reserve 아이스 friends 시나몬 돌체 foam 카푸치노",
  "reserve_nitro": "reserve nitro",
  "rice_cream_coldbrew": "rice 크림 콜드브루",
  "river_peach_fizzio": "river 복숭아 피지오",
  "roasted_sweet_potato_brulee_cream_latte": "roasted 스위트 potato brulee 크림 라떼",
  "rooibos_tea": "rooibos 티",
  "rosemary_tea": "rosemary 티",
  "royal_milk_tea_latte": "royal 밀크 티 라떼",
  "royal_milk_tea_red_bean_bingsu_shake": "royal 밀크 티 red bean bingsu 쉐이크",
  "royal_milk_tea_shake": "royal 밀크 티 쉐이크",
  "ruby_rose_chocolate": "ruby rose 초코",
  "salt_earlgrey_cream_coffee": "salt 얼그레이 크림 커피",
  "salted_caramel_black_milk_tea_with_pearl": "salted 카라멜 블랙 밀크 티 위드 펄",
  "salted_caramel_cream_latte": "salted 카라멜 크림 라떼",
  "salted_sweet_potato_milk_tea": "salted 스위트 potato 밀크 티",
  "screw_strawberry_smoothie": "screw 딸기 스무디",
  "seoul_float": "seoul 플로트",
  "seoul_rice_milk_cold_brew": "seoul rice 밀크 콜드 브루",
  "seoul_sunset_omija_fizzio": "seoul sunset 오미자 피지오",
  "sesame_granita": "sesame granita",
  "shakerato_bianco_over_ice": "shakerato bianco over 아이스",
  "shine_muscat_kale_juice": "샤인 머스캣 kale juice",
  "signature_the_black_coldbrew": "시그니처 the 블랙 콜드브루",
  "smoked_cold_fashioned": "smoked 콜드 fashioned",
  "soybean": "soybean",
  "sparkling_citrus_espresso": "스파클링 시트러스 에스프레소",
  "ssanghwa_latte": "ssanghwa 라떼",
  "ssanghwa_tea": "ssanghwa 티",
  "star_mango_peach_ade": "star 망고 복숭아 ade",
  "star_mango_peach_latte": "star 망고 복숭아 라떼",
  "star_mango_peach_smoothie": "star 망고 복숭아 스무디",
  "starbucks_slammer": "starbucks slammer",
  "steamed_milk": "steamed 밀크",
  "strawberr_acai_lemonade_refreshers": "strawberr acai 레모네이드 refreshers",
  "strawberry_acai_lemonade_refreshers": "딸기 acai 레모네이드 refreshers",
  "strawberry_ade": "딸기 ade",
  "strawberry_banana_juice": "딸기 바나나 juice",
  "strawberry_banana_paiksccino_basic": "딸기 바나나 빽스치노 기본",
  "strawberry_banana_paiksccino_soft": "딸기 바나나 빽스치노 소프트",
  "strawberry_cheesecake_smoothie": "딸기 cheesecake 스무디",
  "strawberry_chocolate_milk_tea": "딸기 초코 밀크 티",
  "strawberry_choux_cream_milk_tea": "딸기 슈 크림 밀크 티",
  "strawberry_cold_foam_chocolate": "딸기 콜드 foam 초코",
  "strawberry_cold_foam_strawberry_latte": "딸기 콜드 foam 딸기 라떼",
  "strawberry_cookie_frappe": "딸기 쿠키 프라페",
  "strawberry_cookie_shake": "딸기 쿠키 쉐이크",
  "strawberry_cookie_smoothie": "딸기 쿠키 스무디",
  "strawberry_cookie_smoothie_pearl": "딸기 쿠키 스무디 펄",
  "strawberry_delight_yogurt_blended": "딸기 delight 요거트 blended",
  "strawberry_foam_jelly_water": "딸기 foam jelly water",
  "strawberry_frappe": "딸기 프라페",
  "strawberry_gelato_dip_choco_latte": "딸기 gelato dip 초코 라떼",
  "strawberry_gelato_lemon_smoothie": "딸기 gelato 레몬 스무디",
  "strawberry_gelato_parfait": "딸기 gelato parfait",
  "strawberry_glazed_cream_frappuccino": "딸기 glazed 크림 프라푸치노",
  "strawberry_green_kiwi_smoothie": "딸기 그린 키위 스무디",
  "strawberry_jewelry_signature_milk_tea": "딸기 쥬얼리 시그니처 밀크 티",
  "strawberry_jewelry_yogurt_crush": "딸기 쥬얼리 요거트 crush",
  "strawberry_jewerly_milk_tea": "딸기 jewerly 밀크 티",
  "strawberry_juice": "딸기 juice",
  "strawberry_latte": "딸기 라떼",
  "strawberry_milk": "딸기 밀크",
  "strawberry_milk_tea": "딸기 밀크 티",
  "strawberry_mochi_milkshake": "딸기 mochi 밀크쉐이크",
  "strawberry_paiksccino_basic": "딸기 빽스치노 기본",
  "strawberry_paiksccino_soft": "딸기 빽스치노 소프트",
  "strawberry_peach_rooibos_tea": "딸기 복숭아 rooibos 티",
  "strawberry_pongcrush": "딸기 퐁크러쉬",
  "strawberry_raspberry_cheese_foam": "딸기 raspberry cheese foam",
  "strawberry_raspberry_choux_yogurt_crush": "딸기 raspberry 슈 요거트 crush",
  "strawberry_real_chocolate_latte": "딸기 real 초코 라떼",
  "strawberry_salty_caramel_frappe": "딸기 salty 카라멜 프라페",
  "strawberry_smoothie": "딸기 스무디",
  "strawberry_yogurt_smoothie": "딸기 요거트 스무디",
  "sujeonggwa": "sujeonggwa",
  "sweet_milk_coffee": "스위트 밀크 커피",
  "sweet_potato_cafe_latte": "스위트 potato 카페 라떼",
  "sweet_potato_latte": "스위트 potato 라떼",
  "sweet_potato_smoothie": "스위트 potato 스무디",
  "sweet_rice_drink": "스위트 rice drink",
  "tangerine_jelly_smoothie": "tangerine jelly 스무디",
  "taro_bubble_tea": "taro 버블 티",
  "taro_jewelry_signature_smoothie": "taro 쥬얼리 시그니처 스무디",
  "taro_jewerly_signature_milk_tea": "taro jewerly 시그니처 밀크 티",
  "taro_milk_tea": "taro 밀크 티",
  "taro_smoothie": "taro 스무디",
  "the_city_real_chocolate_latte": "the city real 초코 라떼",
  "tiramisu_chocolate": "티라미수 초코",
  "toffeenut_latte": "toffeenut 라떼",
  "tomato_juice": "토마토 juice",
  "triple_chocolate_smoothie": "triple 초코 스무디",
  "ube_cafe_latte": "ube 카페 라떼",
  "ube_latte": "ube 라떼",
  "ube_shake": "ube 쉐이크",
  "uiamho_green_grapefruit_fizzio": "uiamho 그린 자몽 피지오",
  "uiamho_purple_lavender_tea_latte": "uiamho purple lavender 티 라떼",
  "vanilla_cafe_mocha": "바닐라 카페 모카",
  "vanilla_coldbrew": "바닐라 콜드브루",
  "vin_chaud": "vin chaud",
  "water": "water",
  "watermelon_juice": "수박 juice",
  "watermelon_oolong_ice_tea": "수박 oolong 아이스 티",
  "watermelon_shower_ice_tea": "수박 shower 아이스 티",
  "watermelon_shower_pearl_crush": "수박 shower 펄 crush",
  "wellness_blueberry_smoothie_bowl": "wellness 블루베리 스무디 bowl",
  "wellness_strawberry_smoothie": "wellness 딸기 스무디",
  "white_chcolate_mocha": "화이트 chcolate 모카",
  "white_chocolate_frappe": "화이트 초코 프라페",
  "white_salt_milk_tea": "화이트 salt 밀크 티",
  "white_tiger_frappuccino": "화이트 tiger 프라푸치노",
  "xo_yakult": "xo yakult",
  "yeosu_sea_grapefruit_fizzio": "yeosu sea 자몽 피지오",
  "yeosu_sea_yuja_blended": "yeosu sea yuja blended",
  "yeosu_shining_hazelnut_coldbrew": "yeosu shining hazelnut 콜드브루",
  "youthberry_tea": "youthberry 티",
  "yuja_ade": "yuja ade",
  "yuja_mint_tea": "yuja 민트 티",
  "yuja_white_tea_vin_chaud": "yuja 화이트 티 vin chaud",
  "yuzu_tea": "유자 티",
  "yuzutea": "yuzutea",
  "zero_boost_ade": "zero boost ade",
  "zesty_lychee_tea": "zesty 리치 티",
} as const;

export const INGREDIENT_ICON_LABELS: Record<IngredientIconKey, string> = {
  "apple": "사과",
  "banana": "바나나",
  "black_sesame": "흑임자",
  "blueberry": "블루베리",
  "caramel": "카라멜",
  "cherry": "체리",
  "chocolate": "초코",
  "cinnamon": "시나몬",
  "coconut": "코코넛",
  "coffee": "커피",
  "cookie": "쿠키",
  "default": "기본",
  "energy": "에너지",
  "fizzy": "탄산",
  "gold_kiwi": "골드키위",
  "grain": "곡물",
  "grape": "포도",
  "grapefruit": "자몽",
  "green_grape": "청포도",
  "hazelnut": "헤이즐넛",
  "hibiscus": "히비스커스",
  "honey": "허니",
  "ice": "얼음",
  "jujube": "대추",
  "kiwi": "키위",
  "leaf": "말차",
  "lemon": "레몬",
  "lime": "라임",
  "lychee": "리치",
  "maesil": "매실",
  "mango": "망고",
  "milk": "우유",
  "mint": "민트",
  "orange": "오렌지",
  "passion_fruit": "패션후르츠",
  "peach": "복숭아",
  "plum": "자두",
  "red_bean": "팥",
  "strawberry": "딸기",
  "sweet_potato": "고구마",
  "teabag": "티백",
  "vanilla": "바닐라",
  "water": "물",
  "white_chcolate": "화이트초코",
  "yogurt": "요거트",
} as const;
